language: php

php:
  - 7.0
  - 7.1
  - nightly

# Save time by only cloning the latest commit.
git:
  depth: 1

matrix:
  allow_failures:
    - php: nightly
  # Note that travis will send multiple build notifications with fast_finish on.
  fast_finish: true

install:
  - travis_retry composer install

before_script:
  # Lint all PHP files except for dependencies.
  - find . -name '*.php' -type f ! -path './vendor/*' | while read file;do php -l "${file}" || exit 1;done

script:
  - mkdir -p tests/logs
  - php vendor/bin/phpunit

after_success:
  # Upload code coverage reports (but only once per build, not for every PHP version).
  # -Z flag to cause build failure if coverage reports fail.
  # HT: https://docs.codecov.io/docs/about-the-codecov-bash-uploader)
  - if [ "7.0" = "$TRAVIS_PHP_VERSION" ]; then
      travis_retry bash <(curl -s https://codecov.io/bash) -f tests/logs/clover.xml -Z;
      travis_retry php vendor/bin/codacycoverage clover tests/logs/clover.xml;
    fi

notifications:
  slack:
    rooms:
      - secure: p3dH7L5CFpk6lrmb7aiHVKwEl8Qpua+Mp3n09rYTE5LhTMaLHczzjqjatNrcyt4GMKSzpJI4axxZ3QXe8KCnl3rr6JwfEHR4jvS4TZbchKFuRfgwF54RMXbUtHfy9fK78LeAo6eQoBliEuDo9Qgk1GTOMtmBv9gOoYRgo3o5sgAAPhF8soD4daNJ70vIwUgZ3bGN7/KTMPweDuNfERJM9w/OrLtYuNKwFPNGSHHkONR5Y5H2lGZtxw9/kZxtvounAFQHwMZfuZpyPSqrqfK8xxJLumTdTrmb14JNm1o4MWelErBHXLmDcTJvJ03mRvEswxbFIePMSZjA913pFZkdR7uWzFo0Z5RRAi3LG9P5s+7UnQDnUxJIaXWYli9j8ikTuPOHXneiYmn4aGvHATvOA+MJ6EDNA1H1dwJ1PSfsFCeNWtvQ1Lt4hfA04GKQxIKoinakj23OmcUKK8eOW7zL3lu6pt1q8J61t33z+Oz/0Vf9i1ebFPNaKTv9M2sMHDLlFstx44WgGihUXhrhudT+1Kc580cYKiXumj8BQeMf9sjfZcn92iDyCk6cYHXdaLNvUqZzQKHAmFEUp/PL7mHd6+EKPz+AzPahfPhfQ3Wainy4woDjLagsODYGOlGicdoAe3SO2LvQO8fiLA7Ew3qGidxQFYOVJoGJgNjewRn9+ZY=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}:%{branch} by %{author}"
      - "%{result} in %{duration}"
      - "(%{commit_message})"

env:
  global:
    # Codacy code coverage
    secure: pS3d4tYot88iQu5AEvxg65EQlIzjuis0T1MkwOGfFNBnYtZg3aYqz4Q/hNIoVApAiE2dNVQPb6dfGoaGtNej6B0EvSGybyc/xmoltrF0NaS2AMxnyaop9Hqp1R91hMw/55w6sqhMx6rsbU+AERHpHF6W6TfQaPe554/84q47Q8LLkIm9yTPmiGTNrfRJExGw6PuMvqPV4huNa7XAr8HMxHnjljM+ONFkY54bwtkSKMOzRKBplyRi3+jOAUapq/HK2yNfWkryy/z/uoyxF5+P4Xpy75QMy5+Y0a3+SFMJdzoQRy6+iQELXC8ZqiubglXzTThhUihP5ptJaAGJIt4y7CBHFeAAPlknJxNjRXzz+e8uZY6m9biSjsmy0NT8yBUlVnIFZpzdu9UZaYVppy5XZ6NhFCPKFexRJgC5FIDgXGR7GpDQdDWAQFtiB+GT5IVfyrgW3Qv3p51vZ64k3NAGs5lyUTU8NRLO9uDrnDCUCu3SVTkV1rOwTvCgeMZxQ3ZX3aKjrgAd2c5POvlejiQZdQeAFBbjlO9CMfkFTQjuYT1wGL8QpaScvZuUaBstnwwzni3oVZvFSqTj9O5Lzn6g0DgRTCCYYb6IXqyuJuSqOqsNMPPxizR0rq4L4dnedluM3rO/PAfxPn9LhJD/jEws/5kFDXt86wIAezkQPygszco=
