version: "2"
services:
  php:
    build: .
    restart: always
    volumes: 
      - ./:/slackemon

  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/slackemon
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres:alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - slackemon_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=slackemon_password
      - POSTGRES_USER=slackemon_user
      - POSTGRES_DB=slackemon_db
      - PGDATA=/var/lib/postgresql/data/pgdata

# Local volume where to store data
# in a persistent way
volumes:
  slackemon_db_data:
  