#!/usr/bin/env bash

# Resets and restarts the Slackemon environment in Docker Compose.
# YOU WILL LOSE ANY DATA STORED IN POSTGRES.

# Safer bash scripts.
set -euxo pipefail

# Stops and removes the Docker Compose containers.
docker-compose down

# Remove Postgres data volume.
docker volume rm slackemon_db_data

# Run user stop script, if it exists.
if [ -f `dirname $0`/stop.local ]; then
   `dirname $0`/stop.local
fi

# Run the start script.
`dirname $0`/start
