#!/usr/bin/env bash

set -x                                 # Output to stdout every command that is run
docker-compose up -d --remove-orphans  # Start the Docker Compose containers detached from the
                                       # current terminal, removing any previous containers
