#!/usr/bin/env bash

set -x                                 # Output everything to stdout
docker-compose up -d --remove-orphans  # Start the Docker Compose containers detached from the
                                       # current terminal, removing any previous containers
