#!/usr/bin/env bash

# Safer bash scripts.
set -euxo pipefail

# Stop the Docker Compose containers.
docker-compose stop

# Run user stop script, if it exists.
if [ -f `dirname $0`/stop.local ]; then
   `dirname $0`/stop.local
fi
